name: Release

on:
  push:
    tags:
      - "v*"

env:
  TAG_NAME: ${{ github.event.ref }}

jobs:
  single_executable:
    name: Release single executable
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: cache deno installation and deno.land dependencies
        uses: actions/cache@v4
        with:
          key: deno-${{ hashFiles('deno.lock') }}
          restore-keys: deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno/deps/https/deno.land
      - name: Install dependencies
        run: deno install
      - name: Build
        run: deno compile --allow-net --allow-env -o dist/mcp-traQ-${{ matrix.target }} --target ${{ matrix.target }} main.ts
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/mcp-traQ-${{ matrix.target }}
  license:
    name: License
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            LICENSE
            README.md
